language: csharp
solution: "./AggregationService/AggregationService.sln"
mono: latest
dotnet: 2.0.0
build: trusty
sudo: required
dist: trusty
notifications:
  email: false

 
jobs:
  include:
  - stage: build
    script: dotnet build "./AggregationService"
  - stage: deploy
    script: skip
    deploy:
        provider: azure_web_apps
        verbose: true
        
    