language: csharp
solution: "./AggregationService/AggregationService.sln"
mono: none
dotnet: 2.0.0
build: trusty
sudo: required
dist: trusty
notifications:
  email: false

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
 
jobs:
  include:
  - stage: build
    script: dotnet build "./AggregationService"
  - stage: deploy
    script: skip
    deploy:
        provider: azure_web_apps
        verbose: true
        
    