language: csharp
solution: "./AggregationService/AggregationService.sln"
mono: latest
dotnet: 2.0.0
script:
 - dotnet restore
build: trusty
sudo: required
dist: trusty
notifications:
  email: false
  
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnu restore
script:
  - dnx -p ./test/[testProjectName]/project.json test -parallel none
  
jobs:
  include:
  - stage: build
    script: dotnet build "./AggregationService"
  - stage: deploy
    script: skip
    deploy:
        provider: azure_web_apps
        verbose: true
        
    